= Board API Guide Document
[choi.ys];
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
//:operation-curl-request-title: Example Request
//:operation-http-response-title: Example Response

[[overview]]
= ** 개요 **

[%hardbreaks]
----
API에 대한 전체적인 설명을 포함합니다.
----

[[overview-http-verbs]]
== ** HTTP 동사 **

---

====
TIP: ** 본 API에서 사용하는 HTTP 동사(verbs)는 가능한 한 표준 HTTP와 REST 규약을 따릅니다.
**
====

|===
| Http Method | Description

| `*GET*`
| *리소스를 조회*

| `*POST*`
| *새 리소스를 생성*

| `*PATCH*`
| *기존 리소스를 수정*

| `*DELETE*`
| *기존 리소스를 삭제*
|===

//https://hyeonstorage.tistory.com/97
[[overview-http-status-codes]]
== ** HTTP 상태 코드 **

---

====
TIP: ** 본 API에서 사용하는 HTTP 상태 코드는 가능한 한 표준 HTTP와 REST 규약을 따릅니다.
**
====

|===
| Http Status Code | Description

| `*200 OK*`
| 요청이 성공적으로 처리 되었습니다.
성공의 의미는 `*HTTP Method*` 에 따라 달라집니다.

| `*201 Created*`
| 요청이 성공적이었으며 그 결과로 새로운 리소스가 생성되었습니다. +
이 응답은 일반적으로 `POST` 요청 또는 일부 `PUT` 요청 이후에 따라옵니다.
응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있습니다.

| `*204 No Content*`
| `*POST*` 성공 상태 응답 코드는 요청이 성공했으나 클라이언트가 현재 페이지에서 벗어나지 않아도 된다는 것을 나타냅니다. +
기본값에서 204 응답은 캐시에 저장할 수 있습니다. +
캐시에서 가져온 응답인 경우 ETag 헤더를 포함합니다.

| `*400 Bad Request*`
| 잘못된 요청을 보낸 경우.
응답 본문에 더 오류에 대한 정보가 담겨있다.

| `*401 Unauthorized*`
| 인증 실패

| `*403 Forbidden*`
| 접근 권한 없음

| `*404 Not Found*`
| 요청한 리소스가 없음

| `*415 Unsupported Media Type*`
| 요청한 `Midea Type` 을 지원하지 않음

| `*429 Too Many Requests*`
| 일정 기간내 너무 많은 요청이 접수됨
|===

[[overview-hypermedia]]
== ** 하이퍼미디어 **

---

----
- 본 API는 하이퍼미디어와 사용하며, 응답에 담겨있는 리소스는 관계된 다른 리소스에 대한 링크를 가지고 있습니다.
- 응답은 [Hypertext Application from resource to resource. Language (HAL)] 형식을 따릅니다.
- 링크는 '_links' 라는 키로 제공합니다.
- 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 합니다.
----

[[common]]
= ** 공통사항 **
---


[[common-domain]]
== ** 도메인 정보 **

TIP: ** 도메인 정보 **

----
API 호출 시 Endpoint구성에 필요한 도메인 정보를 제공합니다.
----

|===
| 환경 | 도메인

| DEV | dev-api.board.io

| STG | stg-api.board.io

| SANDBOX | sandbox-api.board.io

| PRD | api.board.io
|===

[[common-request]]
== ** 요청 메세지 구조 **

TIP: ** 요청 메세지 구조 **

----
API 호출에 필요한 요청 메세지 구조에 대한 정보를 제공합니다.
 - 요청 파라미터는 CamelCase 구조를 따릅니다.
----

[[common-response]]
== ** 응답 메세지 구조 **

TIP: ** 응답 메세지 구조 **

----
API 호출 시 응답 메세지 구조에 대한 정보를 제공합니다.
----

---


[[common-response-pagination]]
=== ** Pagination **

TIP: ** Pagination **

----
목록 API 호출 시 응답 내 페이징 처리에 대한 구조 정보를 제공합니다.
----

---

[[common-response-errors]]
=== ** Error **

IMPORTANT: ** API 호출 시 에러가 발생했을 때 (상태 코드 >= 400), 응답 본문에 해당 문제를 기술한 JSON 객채를 반환합니다.
에러 객체는 다음과 같은 구조로 구성되어 있습니다.
**

----
{
    timestamp : 오류 일시
    code : 오류 코드
    message : 오류 사유
    method : 요청 Http Method
    path : 요청 Http URI
    errorDetails : {
        object : 오류 객체
        field : 오류 항목
        code : 오류 코드
        rejectMessage : 오류 사유
        rejectedValue : 오류 파라미터 값
    }
}
----


//include::{snippets}/response-fields.adoc[]


WARNING: ** 예를 들어, 잘못된 요청으로 게시글을 생성하려고 했을 때 다음과 같은 `400 Bad Request` 응답을 반환합니다.
**

----
{
  "timestamp": "2021-09-28 02:37:31",
  "code": "METHOD_ARGUMENT_NOT_VALID",
  "message": "잘못된 요청입니다. 요청값을 확인해주세요.",
  "method": "POST",
  "path": "/post",
  "errorDetails": [
    {
      "object": "postCreateRequest",
      "field": "title",
      "code": "Size",
      "rejectMessage": "게시글 제목은 1~50자 이내로 입력하세요.",
      "rejectedValue": ""
    },
    {
      "object": "postCreateRequest",
      "field": "title",
      "code": "NotBlank",
      "rejectMessage": "제목은 필수 입력 사항입니다.",
      "rejectedValue": ""
    },
    {
      "object": "postCreateRequest",
      "field": "content",
      "code": "NotBlank",
      "rejectMessage": "본문은 필수 입력 사항입니다.",
      "rejectedValue": ""
    }
  ]
}
----


//include::{snippets}/errors/http-response.adoc[]


[[resources]]
= ** API **
---


[[resources-index]]
== ** 목차 **

NOTE: ** Index API **

----
Index API는 서비스 진입점을 제공 합니다.
----

[[resources-index-access]]
=== ** 목차 조회 : `*GET*` Index **

====
`*GET*` 요청을 사용하여 목차에 접근할 수 있습니다.

operation::index-controller-test/index[snippets='response-body,http-response,links']

====

[[resources-member]]
== ** 회원 **

NOTE: ** Member API **

----
Member API는 사용자 관련 API Interface를 제공 합니다.
----

[[resources-member-create]]
=== ** 게시글 생성 : `*POST*` Member **

====
`*POST*` 요청을 사용하여 게시글을 생성할 수 있습니다.

operation::member-controller-test/signup[snippets='http-request,request-headers,request-body,request-fields,response-body,response-fields,http-response,links']
====


[[resources-post]]
== ** 게시글 **

NOTE: ** Post API **

----
Post API는 게시글 관련 API Interface를 제공 합니다.
----

[[resources-post-create]]
=== ** 게시글 생성 : `*POST*` Post **

====
`*POST*` 요청을 사용하여 게시글을 생성할 수 있습니다.

operation::post-controller-test/create[snippets='http-request,request-headers,request-body,request-fields,response-body,response-fields,http-response,links']
====


[[resources-post-access]]
=== ** 게시글 조회 : `*GET*` Post **
====
`*GET*` 요청을 사용하여 게시글을 조회할 수 있습니다.

operation::post-controller-test/find-by-id-and-display-true[snippets='http-request,request-headers,path-parameters,response-fields,response-body,http-response']
====


[[resources-post-update]]
=== ** 게시글 수정 : `*PATCH*` Post **
====
`*PATCH*` 요청을 사용하여 게시글을 수정할 수 있습니다.

operation::post-controller-test/update[snippets='http-request,request-headers,path-parameters,request-fields,request-body,response-fields,response-body,http-response']
====


[[resources-post-delete]]
=== ** 게시글 삭제 : `*DELETE*` Post **
====
`*DELETE*` 요청을 사용하여 게시글을 수정할 수 있습니다.

operation::post-controller-test/delete-post[snippets='http-request,request-headers,path-parameters,http-response']
====

---