= Board API Guide Document
[choi.ys];
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toc-title: 목차
:toclevels: 5
:sectlinks:

[[overview]]
= ** 개요 **

[%hardbreaks]
----
API에 대한 전체적인 설명을 포함합니다.
----

[[overview-http-verbs]]
== ** HTTP 동사 **
****
TIP: ** 본 API에서 사용하는 HTTP 동사(verbs)는 가능한 한 표준 HTTP와 REST 규약을 따릅니다. **

|===
| Http Method | Description

| `*GET*`
| *리소스를 조회*

| `*POST*`
| *새 리소스를 생성*

| `*PATCH*`
| *기존 리소스를 수정*

| `*DELETE*`
| *기존 리소스를 삭제*
|===
****

//https://hyeonstorage.tistory.com/97
[[overview-http-status-codes]]
== ** HTTP 상태 코드 **
****
TIP: ** 본 API에서 사용하는 HTTP 상태 코드는 가능한 한 표준 HTTP와 REST 규약을 따릅니다. **

[cols="1h,2l,4s,4m"]
|===
| Code | Message | Error Code | Description

| 200
| OK
| -
| 요청이 성공적으로 처리 되었음을 의미합니다.
성공의 의미는 `*HTTP Method*` 에 따라 달라집니다.

| 201
| Created
| -
| 요청이 성공적이었으며, 그 결과 새로운 리소스가 생성되었습니다. +
이 응답은 일반적으로 `*POST*` 요청 또는 일부 `*PUT*` 요청 이후에 따라옵니다.
응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있습니다.

| 204
| No Content
| -
| 요청이 성공적이었으며, 반환할 응답 바디가 없습니다.
`*POST*` 성공 상태 응답 코드는 요청이 성공했으나 클라이언트가 현재 페이지에서 벗어나지 않아도 된다는 것을 나타냅니다. +
기본값에서 204 응답은 캐시에 저장할 수 있습니다. +
캐시에서 가져온 응답인 경우 ETag 헤더를 포함합니다.

| 400
| Bad Request
| HTTP_MESSAGE_NOT_READABLE
| 요청값을 확인할 수 없는 경우

| 400
| Bad Request
| METHOD_ARGUMENT_TYPE_MISMATCH
| 요청값의 자료형이 잘못된 경우

| 400
| Bad Request
| METHOD_ARGUMENT_NOT_VALID
| 유효하지 못한 요청인 경우

| 401
| Unauthorized
| BAD_CREDENTIALS
| 인증 실패: 잘못된 자격 증명인 경우

| 401
| Unauthorized
| AUTHENTICATION_CREDENTIALS_NOT_FOUND
| 인증 실패: 자격 증명 정보를 찾을 수 없는 경우

| 403
| Forbidden
| UNAUTHORIZED
| 접근 권한 없음 : 유효한 자격증명이 아닌 경우

| 403
| Forbidden
| ACCESS_DENIED
| 접근 권한 없음 : 유효한 자격증명이 아닌 경우

| 404
| Not Found
| RESOURCE_NOT_FOUND
| 요청에 해당하는 자원을 찾을 수 없는 경우

| 405
| Method Not Allowed
| HTTP_REQUEST_METHOD_NOT_SUPPORTED
| 허용하지 않는 Http Method 요청인 경우

| 405
| Not Acceptable
| HTTP_MEDIA_TYPE_NOT_ACCEPTABLE
| 지원하지 않는 Accept Type인 경우

| 415
| Unsupported Media Type
| HTTP_MEDIA_TYPE_NOT_SUPPORTED
| 요청한 `Midea Type` 을 지원하지 않는 경우

| 429
| Too Many Requests
| TOO_MANY_REQUEST
| 일정 기간내 너무 많은 요청이 접수됨
|===
****

[[overview-hypermedia]]
== ** 하이퍼미디어 **
****
TIP: ** 본 API의 응답에는 하이퍼미디어 정보를 포함합니다.**

[horizontal]
- 본 API는 하이퍼미디어와 사용하며, 응답에 담겨있는 리소스는 관계된 다른 리소스에 대한 링크를 가지고 있습니다.
- 응답은 [Hypertext Application from resource to resource. Language (HAL)] 형식을 따릅니다.
- 링크는 '_links' 라는 키로 제공합니다.
- 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 합니다.
****

[[common]]
= ** 공통사항 **

[[common-domain]]
== ** 도메인 정보 **
****
TIP: ** API 호출 시 Endpoint구성에 필요한 도메인 정보를 제공합니다. **
|===
| 환경 | 도메인

| DEV | dev-api.board.io

| STG | stg-api.board.io

| SANDBOX | sandbox-api.board.io

| PRD | api.board.io
|===
****

[[common-request]]
== ** 요청 메세지 구조 **
====
TIP: ** API 호출에 필요한 요청 메세지 구조에 대한 정보를 제공합니다. 요청 파라미터는 CamelCase 구조를 따릅니다. **

====

[[common-response]]
== ** 응답 메세지 구조 **

[[common-response-pagination]]
=== ** Pagination **
====

TIP: ** 목록 API 호출 시 응답 내 페이징 처리에 대한 구조 정보를 제공합니다. **

operation::common-docs-snippet-controller-test/common-pagination-response[snippets='response-fields']
====


[[common-response-errors]]
=== ** Error **
====
IMPORTANT: ** API 호출 시 에러가 발생했을 때 (상태 코드 >= 400), 응답 본문에 해당 문제를 기술한 JSON 객체를 반환합니다.
에러 응답 객체는 다음과 같은 구조로 구성되어 있습니다. **

operation::post-controller-test/create_-fail_-cause_-no-argument[snippets='response-fields,response-body']

WARNING: ** 예를 들어, 잘못된 요청으로 게시글을 생성하려고 했을 때 다음과 같은 `400 Bad Request` 응답을 반환합니다. **

operation::post-controller-test/create_-fail_-cause_-invalid-argument[snippets='response-fields,http-request,http-response']
====

[[resources]]
= ** API **

[[resources-index]]
== ** 목차 **

NOTE: ** Index API는 서비스 진입점을 제공 합니다. **

[[resources-index-access]]
=== ** 목차 조회 : `*GET*` Index **
[example]
`*GET*` 요청을 사용하여 목차에 접근할 수 있습니다.

====
//`*GET*` 요청을 사용하여 목차에 접근할 수 있습니다.

operation::index-controller-test/index[snippets='http-request,http-response,links']

====

[[resources-member]]
== ** 회원 **

NOTE: Member API는 사용자 관련 API Interface를 제공 합니다.

[[resources-create-member]]
=== ** 회원 생성 : `*POST*` Member **
[example]
`*POST*` 요청을 사용하여 회원가입 할 수 있습니다.

====

operation::member-controller-test/signup[snippets='http-request,request-headers,request-fields,http-response,response-fields,links']
====

[[resources-authorization]]
== ** 인증 **

NOTE: ** Authorization API는 인증 관련 API Interface를 제공 합니다. **

[[resources-login]]
=== ** 로그인 : `*POST*` Login **
[example]
`*POST*` 요청을 사용하여 로그인 할 수 있습니다.

====

operation::login-controller-test/login[snippets='http-request,request-headers,request-fields,http-response,response-fields,links']
====

[[resources-refresh]]
=== ** 토큰 갱신 : `*POST*` Refresh **
[example]
`*POST*` 요청을 사용하여 토큰을 갱신 할 수 있습니다.

====

operation::login-controller-test/refresh[snippets='http-request,request-headers,http-response,response-fields']
====

[[resources-post]]
== ** 게시글 **

NOTE: ** Post API는 게시글 관련 API Interface를 제공 합니다. **

[[resources-create-post]]
=== ** 게시글 생성 : `*POST*` Post **
[example]
`*POST*` 요청을 사용하여 게시글을 생성할 수 있습니다.

====

operation::post-controller-test/create[snippets='http-request,request-headers,request-fields,http-response,response-fields,links']
====

[[resources-get-an-post]]
=== ** 게시글 조회 : `*GET*` Post **
[example]
`*GET*` 요청을 사용하여 게시글을 조회할 수 있습니다.

====

operation::post-controller-test/find-by-id-and-display-true[snippets='http-request,request-headers,path-parameters,http-response,response-fields']
====

[[resources-update-an-post]]
=== ** 게시글 수정 : `*PATCH*` Post **
[example]
`*PATCH*` 요청을 사용하여 게시글을 수정할 수 있습니다.

====

operation::post-controller-test/update[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']
====

[[resources-delte-an-post]]
=== ** 게시글 삭제 : `*DELETE*` Post **
[example]
`*DELETE*` 요청을 사용하여 게시글을 수정할 수 있습니다.

====

operation::post-controller-test/delete-post[snippets='http-request,request-headers,path-parameters,http-response']
====

[[resources-search-posts]]
=== ** 게시글 검색 : `*Search*` Post **
[example]
`*GET*` 요청을 사용하여 게시글을 검색할 수 있습니다.

====

operation::post-controller-test/search[snippets='http-request,request-headers,http-response,request-parameters']
====